components {
  id: "enemy_1"
  component: "/game/enemy/enemy_1/enemy_1.script"
}
embedded_components {
  id: "spinemodel"
  type: "spinemodel"
  data: "spine_scene: \"/game/enemy/enemy.spinescene\"\n"
  "default_animation: \"idle\"\n"
  "skin: \"enemy_1\"\n"
  "material: \"/defold-spine/assets/spine.material\"\n"
  ""
}
embedded_components {
  id: "co"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"enemy\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -1.0\n"
  "      y: 17.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -5.0\n"
  "      y: 35.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "  }\n"
  "  data: 15.801176\n"
  "  data: 15.2216215\n"
  "  data: 10.0\n"
  "  data: 7.7373643\n"
  "  data: 5.2367225\n"
  "  data: 12.38688\n"
  "}\n"
  ""
}
