components {
  id: "enemy_0"
  component: "/game/enemy/enemy_0/enemy_0.script"
}
embedded_components {
  id: "spinemodel"
  type: "spinemodel"
  data: "spine_scene: \"/game/enemy/enemy.spinescene\"\n"
  "default_animation: \"idle\"\n"
  "skin: \"enemy_0\"\n"
  "material: \"/defold-spine/assets/spine.material\"\n"
  ""
}
embedded_components {
  id: "co"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"enemy\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -1.0\n"
  "      y: 31.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 3.0\n"
  "      y: 8.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 1\n"
  "    count: 3\n"
  "  }\n"
  "  data: 21.21669\n"
  "  data: 7.47509\n"
  "  data: 10.0\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
