components {
  id: "enemy_5"
  component: "/game/enemy/enemy_5/enemy_5.script"
}
embedded_components {
  id: "spinemodel"
  type: "spinemodel"
  data: "spine_scene: \"/game/enemy/enemy.spinescene\"\n"
  "default_animation: \"idle\"\n"
  "skin: \"enemy_5\"\n"
  "material: \"/defold-spine/assets/spine.material\"\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"enemy\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 20.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 16.0\n"
  "      y: 25.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "  }\n"
  "  data: 11.023748\n"
  "  data: 19.634747\n"
  "  data: 11.2\n"
  "  data: 9.052256\n"
  "  data: 21.24508\n"
  "  data: 9.2\n"
  "}\n"
  ""
}
embedded_components {
  id: "minefactory"
  type: "factory"
  data: "prototype: \"/game/bullets/mine.go\"\n"
  ""
}
embedded_components {
  id: "coconfactory"
  type: "factory"
  data: "prototype: \"/game/bullets/cocon.go\"\n"
  ""
}
