components {
  id: "enemy"
  component: "/game/enemy/enemy.script"
}
embedded_components {
  id: "enemy_75"
  type: "sprite"
  data: "default_animation: \"enemy_75\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/game/enemy/enemies.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 1.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"enemy_300_coll\"\n"
  "  }\n"
  "  data: 135.73363\n"
  "  data: 133.92159\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "enemy_50"
  type: "sprite"
  data: "default_animation: \"enemy_50\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/game/enemy/enemies.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "enemy_100"
  type: "sprite"
  data: "default_animation: \"enemy_100\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "size {\n"
  "  x: 50.0\n"
  "  y: 50.0\n"
  "}\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/game/enemy/enemies.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "enemy_200"
  type: "sprite"
  data: "default_animation: \"enemy_200\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "size {\n"
  "  x: 75.0\n"
  "  y: 75.0\n"
  "}\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/game/enemy/enemies.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "enemy_300"
  type: "sprite"
  data: "default_animation: \"enemy_300\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "size {\n"
  "  x: 200.0\n"
  "  y: 200.0\n"
  "}\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/game/enemy/enemies.atlas\"\n"
  "}\n"
  ""
}
